name: EasyMessages
main: easymessages.EasyMessages
version: 1.0.0
api: 1.0.0
load: POSTWORLD
author: Gamecrafter
description: Send messages to your players with ease!
website: https://github.com/Viperize/EasyMessages-Nukkit
permissions:
 easymessages:
  default: op
  children:
   easymessages.action:
    default: op
    children:
     easymessages.action.color:
      default: op
   easymessages.command:
    default: op
    children:
     easymessages.command.easymessages:
      default: op